### ISSUE TITLE
Encountered this error

### ISSUE THREAD

**Issue by pranaypratyush** [fastai/fastprogress#29]
```
Traceback (most recent call last):                                                                                       
  File "depth_fast.py", line 82, in <module>
    ftrain.fit_one_cycle(main_model, 1)
  File "/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/train.py", line 22, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py", line 191, in fit
    callbacks=self.callbacks+callbacks)
  File "/home/pranay/anaconda3/lib/python3.6/site-packages/fastai/basic_train.py", line 92, in fit
    for xb,yb in progress_bar(data.train_dl, parent=pbar):
ValueError: too many values to unpack (expected 2)
```

**Comment by sgugger** [comment]
This is unrelated to fastprogress, as it's most likely a problem with `data.train_dl`. Closing this here, but you can open an issue on fastai. Please include a reproducible example of the bug or we can't help and fix it.
