### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2588'

### ISSUE THREAD

**Issue by alberduris** [fastai/fastprogress#37]
I am using Fast-bert, which uses _fastprogress_ under the hood, an encountered an encoding issue while running a script from a _CentOS Linux_ server terminal.

Please note that this same issue is referred in #21, and the workaround of setting the `LC_ALL `environment variable to `C.UTF-8` does not work, but it works to set it to `en_US.UTF-8`.

`$ setenv LC_ALL en_US.UTF-8`

Anyway, I think this should be solved, as this is just a temporal workaround (you have to set it again every day) and it is a simple encoding error which is severely breaking other libraries which depends on _fastprogress_. 

This is the full traceback, but in summary the problem is the `'\u2588'` (_full-block_) character, which is used to fill the progress bar.

```
Traceback (most recent call last):
  File "Train-FastBert.py", line 92, in <module>
    tr_manager.train(data_holder)
  File "/gscratch2/users/ablanco061/PhD_workspace/MIMICOsa_workspace/scripts/fast-bert/train/tr_bin/train_manager.py", line 20, in train
    self.custom_model.learner.fit(data_holder.epochs, data_holder.learning_rate, validate=True)
  File "/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fast_bert/learner_cls.py", line 276, in fit
    for step, batch in enumerate(progress_bar(train_dataloader, parent=pbar)):
  File "/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 75, in __iter__
    if self.auto_update: self.update(i+1)
  File "/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 92, in update
    self.update_bar(val)
  File "/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 104, in update_bar
    else: self.on_update(val, f'{100 * val/self.total:.2f}% [{val}/{self.total} {elapsed_t}<{remaining_t}{end}]')
  File "/gscratch2/users/ablanco061/libs_custom/alber_venv_gpu/lib/python3.6/site-packages/fastprogress/fastprogress.py", line 274, in on_update
    if printing(): WRITER_FN(to_write, end = '\r')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2588' in position 14: ordinal not in range(256)
```

I guess that a potencial solution could be checking the encoding which the user has and selecting the corresponding fill character (one that does not cause an encoding error)

If you need something else in order to fix the error, please count on me.

**Comment by sgugger** [comment]
You can always change the fill char by importing `ConsoleProgressBar` then doing:
```
ConsoleProgressBar.fill = 'X'
```
(or whatever you want). 

For a more general fix, I added a try block to print the fill char and fallback to X if it fails.

**Comment by alberduris** [comment]
Great! I didn't know the trick to change the fill chat, good to know 😀 

Thank you very much for the quick fix!
