### ISSUE TITLE
ImportError: 'master_bar' from 'fastprogress'

### ISSUE THREAD

**Issue by fuad3600** [fastai/fastprogress#52]
Hi,

I am trying to import fastai and getting this error:

from fastai.imports import *
Traceback (most recent call last):

  File "<ipython-input-7-9f9378ae0f2a>", line 1, in <module>
    from fastai.imports import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastai\__init__.py", line 1, in <module>
    from .basic_train import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastai\basic_train.py", line 2, in <module>
    from .torch_core import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastai\torch_core.py", line 2, in <module>
    from .imports.torch import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastai\imports\__init__.py", line 1, in <module>
    from .core import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\fastai\imports\core.py", line 15, in <module>
    from fastprogress import master_bar, progress_bar

ImportError: cannot import name 'master_bar' from 'fastprogress' (C:\ProgramData\Anaconda3\lib\site-packages\fastprogress\__init__.py)

I am using anaconda (spyder) and I have installed fastai and fastprogress with following codes from anaconda prompt
conda install -c fastai fastprogress 
conda install -c fastai fastai

Any suggestions? Thank you in advance.

**Comment by fuad3600** [comment]
I solved it by deleting line
`from fastprogress import master_bar, progress_bar` from 
"C:\ProgramData\Anaconda3\lib\site-packages\fastai\imports\torch.py"
